from pathlib import Path
import json,re,html
ROOT=Path(__file__).resolve().parents[1];D=ROOT/'dist';data=json.loads((ROOT/'src/kerala-content.json').read_text());esc=html.escape
A='/assets/kerala/';WA='https://wa.me/919947478328'
def img(file,alt,cls=''):
 return f'<img class="{cls}" src="{A+file}" alt="{esc(alt)}" loading="lazy" decoding="async">'
def btn(label,url='/contact',cls=''):
 return f'<a class="button {cls}" href="{url}">{label}<span aria-hidden="true">↗</span></a>'
def eyebrow(s):return f'<span class="eyebrow"><span aria-hidden="true">✳</span> {s} <span aria-hidden="true">✳</span></span>'
def heading(k,t,p='',center=False):return f'<div class="section-heading {"center" if center else ""}" data-reveal>{eyebrow(k)}<h2>{t}</h2>{f"<p>{p}</p>" if p else ""}</div>'
nav='''<a class="skip" href="#content">Skip to content</a><header class="header"><button class="menu-toggle" aria-expanded="false" aria-controls="mobile-menu" aria-label="Open menu"><span class="menu-icon" aria-hidden="true"><i></i><i></i><i></i><i></i></span><span class="menu-label">Menu</span></button><a class="brand" href="/" aria-label="Arafath Tours home"><strong>Arafath</strong><small>TOURS</small></a><a class="nav-cta" href="/contact">Plan a Trip <span aria-hidden="true">↗</span></a><nav id="mobile-menu" aria-label="Site navigation" hidden><a href="/tour">The experience</a><a href="/tours">Things to do</a><a href="/traveler-stories">Village gallery</a><a href="/cabs">Cab journeys</a><a href="/location">Explore Kerala</a><a href="/blog">Journal</a><a href="/about">About Arafath</a><a href="/contact">Plan your trip ↗</a></nav></header>'''
def video(file,poster,kind):
 return f'<video class="ambient-video" autoplay muted loop playsinline preload="metadata" poster="/assets/video/{poster}" aria-label="{kind}" data-ambient><source src="/assets/video/{file}" type="video/mp4"></video><button class="video-toggle" aria-label="Pause background video" aria-pressed="false">Ⅱ <span>Pause film</span></button>'
def footer():return f'''<section class="closing">{video('closing-sunset.mp4','closing-poster.jpg','Sunset beach film')}<div class="closing-content" data-reveal>{eyebrow('A little closer to the extraordinary')}<h2>Come for the view.<br>Stay for the <em>feeling.</em></h2>{btn('Let’s plan your journey','/contact','light')}</div></section><footer class="footer wrap"><div class="footer-top"><a class="brand" href="/"><strong>Arafath</strong><small>TOURS & TRAVELS</small></a><p>Slow journeys. Local stories.<br>Beautifully Kerala.</p><div><a href="tel:+919947478328">+91 99474 78328 ↗</a><a href="mailto:Arafathappu52@gmail.com">Arafathappu52@gmail.com ↗</a></div></div><div class="footer-links"><a href="/about">Our story</a><a href="/tour">Vaikom tour</a><a href="/cabs">Cab facilities</a><a href="/blog">Kerala journal</a><a href="/contact">Contact</a></div><div class="footer-bottom"><span>© 2026 Arafath Tours · Fort Kochi, Kerala</span><a class="site-credit" href="https://aiavro.com" target="_blank" rel="noopener">Designed by AIavro ↗</a><a href="#top">Back to top ↑</a></div></footer>'''
def shell(title,body,home=False):return f'''<!doctype html><html lang="en" id="top"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#ffffff"><title>{esc(title)} | Arafath Tours</title><meta name="description" content="Discover Vaikom village backwaters with Arafath Tours. Boat rides, local crafts, Kerala lunch and cab journeys from Fort Kochi."><link rel="icon" href="/assets/logo-dark.svg" type="image/svg+xml"><link rel="stylesheet" href="/fonts.css"><link rel="stylesheet" href="/design.css"><script defer src="/assets/vendor/gsap.min.js"></script><script defer src="/assets/vendor/ScrollTrigger.min.js"></script><script defer src="/assets/vendor/lenis.min.js"></script><script defer src="/design.js"></script></head><body class="{'home' if home else 'inner-page'}">{nav}<main id="content">{body}</main>{footer()}<dialog id="photo-dialog" aria-label="Village gallery photograph"><button class="dialog-close" aria-label="Close photograph">×</button><img alt=""><div class="photo-caption"><p></p><div><button data-photo-prev aria-label="Previous photograph">←</button><button data-photo-next aria-label="Next photograph">→</button></div></div></dialog><dialog id="cab-dialog" aria-labelledby="cab-title"><button class="dialog-close" aria-label="Close enquiry">×</button>{eyebrow('Kerala cab journeys')}<h2 id="cab-title">Where shall we <em>go?</em></h2><p>Share your plans. We’ll confirm the route and vehicle with you.</p><form id="cab-form"><label>Your name<input name="Name" autocomplete="name" required></label><label>Phone / WhatsApp<input type="tel" name="Phone" autocomplete="tel" required></label><label>Pickup location<input name="Pickup" required></label><label>Destination<input name="Destination" required></label><label>Travel date<input name="Date" type="date" required></label><label>Pickup time<input name="Time" type="time" required></label><label>Passengers<input name="Passengers" type="number" min="1" max="30" value="2" required></label><label>Vehicle<select name="Vehicle"><option>Help me choose</option><option>Maruti Dzire</option><option>Toyota Innova</option><option>Innova Crysta</option></select></label><label class="wide">Journey details<textarea name="Notes" rows="3" placeholder="Return trip, extra stops or luggage"></textarea></label><button class="button wide" type="submit">Continue on WhatsApp <span>↗</span></button><small class="wide">Review and send the enquiry in WhatsApp. The team will confirm your booking.</small></form></dialog></body></html>'''
def save(path,title,body,home=False):
 p=D/path/'index.html';p.parent.mkdir(parents=True,exist_ok=True);p.write_text(shell(title,body,home))
def intro(k,t,p):return f'<section class="page-intro wrap">{eyebrow(k)}<h1>{t}</h1><p>{p}</p></section>'
def stamps():
 items=[('01','Village','craft visits','Handmade traditions','lemon'),('02','Pickup','& drop','From your hotel','peach'),('03','Kerala','lunch','A local pause','pink'),('04','Every','day','Daily departures','sage')]
 return '<div class="stamps">'+''.join(f'<div class="stamp-wrap"><div class="stamp {c}" data-stamp><span class="stamp-number">✳ {n} ✳</span><strong>{a}<br><em>{b}</em></strong><small>{s}</small></div></div>' for n,a,b,s,c in items)+'</div>'
def promise():return f'<section class="section wrap promise">{heading("The Arafath experience","We don’t just book trips.<br>We craft <em>journeys</em> that<br>stay with you for a <em>lifetime.</em>",center=True)}{stamps()}</section>'
experiences=[('vaikom-31-1.jpg','Bamboo boat on a Vaikom canal','Backwaters','Bamboo boat, quieter waters','Three unhurried hours through village backwaters, with life unfolding along the banks.','3-hour boat ride'),('coir.jpg','Artisans making coir rope in Kerala','Local crafts','The village, by hand','Meet Kerala’s craft traditions through coir rope making and village demonstrations.','Included in your day'),('sadya.webp','Kerala banana leaf feast','Kerala lunch','A taste of local life','Pause for a traditional Kerala lunch before your small canal ride. Menu confirmed by the team.','Lunch included'),('vaikom-31-2.jpg','Guests holding woven coconut leaves','Village life','Coconut leaf weaving','Discover how local hands turn coconut leaves into traditional thatched roofing.','Village craft visit'),('vaikom-30.jpg','Guests travelling in a covered village boat','Boat rides','Time on the water','Settle into the shade and enjoy a slower rhythm with your fellow travellers.','Daily departures'),('vaikom-32-2.jpg','Village coir rope demonstration with visitors','Local crafts','Stories from local hands','Get closer to the people and skills behind Vaikom’s village experience.','Part of the full-day tour')]
def cards(items):return '<div class="cards">'+''.join(f'<a class="tour-card" data-category="{cat}" href="/tour" data-reveal><div class="card-photo">{img(f,alt)}<span class="tag">{cat}</span><span class="card-arrow">↗</span></div><div class="card-body"><h3>{t}</h3><p>{d}</p><div class="card-meta"><span>{m}</span><span>Explore ↗</span></div></div></a>' for f,alt,cat,t,d,m in items)+'</div>'
def ribbon():return '<section class="ribbon" aria-label="Explore Kerala"><div class="ribbon-track">'+''.join('<span>Vaikom</span><b>✳</b><span><em>Fort Kochi</em></span><b>✳</b><span>Munnar</span><b>✳</b><span><em>Alappuzha</em></span><b>✳</b>' for _ in range(3))+'</div><div class="ribbon-note">ONE BEAUTIFUL STATE. A WORLD OF LITTLE DISCOVERIES.</div></section>'
def stats():return f'''<section class="tour-details section"><div class="wrap"><div class="details-top" data-reveal><div>{eyebrow('Your full-day Vaikom tour')}<h2>A whole day.<br><em>Beautifully spent.</em></h2></div><div class="tour-price"><span>The complete experience</span><strong>₹1,900<small>/ person</small></strong><p>Boat rides, village craft visits,<br>Kerala lunch and hotel transfers.</p>{btn('Enquire about your date',WA+'?text=Hello%20Arafath%2C%20I%20would%20like%20to%20enquire%20about%20the%20Vaikom%20tour.')}</div></div><div class="stats-grid"><article data-reveal><span class="step-number">01 / THE MORNING</span><strong>8:30 <em>AM</em></strong><h3>Your day begins</h3><p>Hotel pickup between 8:30 and 8:45 AM.</p></article><article data-reveal><span class="step-number">02 / THE BACKWATERS</span><strong>3 <em>hours</em></strong><h3>Take the slow route</h3><p>A bamboo boat journey through village backwaters.</p></article><article data-reveal><span class="step-number">03 / AFTER LUNCH</span><strong>45 <em>min</em></strong><h3>A little closer to nature</h3><p>A small canal ride, then hotel return around 4:00–4:30 PM.</p></article></div></div></section>'''
def gallery(full=False):
 indices=range(8) if full else [0,2,4,5]
 return f'<section class="section wrap" id="gallery">{heading("Moments from the tour","The people make<br>the <em>memories.</em>","Real moments from Arafath’s village experience, from the waterway to the craft workshop.",True)}<div class="gallery-grid">'+''.join(f'<button class="gallery-item" data-photo="{i}" data-reveal>{img(data["gallery"][i][0],data["gallery"][i][2])}<span><strong>{data["gallery"][i][1]}</strong><b>↗</b></span></button>' for i in indices)+f'</div>{"" if full else "<div class=section-end>"+btn("Explore the village gallery","/traveler-stories")+"</div>"}</section>'
def cabsection(full=False):
 routes=''.join(f'<button class="route-row" data-route="{esc(a)}"><span><strong>{a}</strong><small>{b}</small></span><b>↗</b></button>' for a,b in data['routes'])
 fleet=''
 if full:
  fleet='<div class="fleet">'+''.join(f'<article class="fleet-card" data-reveal><div class="fleet-stage">{img(file,name,"fleet-car")}</div><span class="eyebrow">{desc}</span><h3>{name}</h3><button class="text-button" data-vehicle="{name}">Enquire about this car ↗</button></article>' for file,name,desc in [('dzire-isolated.png','Maruti Dzire','Sedan · Up to 4 guests'),('innova-isolated.png','Toyota Innova','SUV · Up to 6 guests'),('crysta-official.webp','Innova Crysta','Premium comfort')])+'</div><p class="fleet-note">Model images are illustrative. Vehicle model year and colour are confirmed when booking.</p>'
 return f'<section class="section cab-section"><div class="wrap"><div class="cab-layout"><div data-reveal>{eyebrow("Arafath cab facilities")}<h2>From landing<br>to <em>unwinding.</em></h2><p>Airport pickups, local journeys and outstation escapes. Tell us where you’re headed — we’ll help with the road ahead.</p><div class="cab-line">FORT KOCHI <span>— ✳ —</span> KERALA</div><button class="button" data-route="Custom Kerala journey">Plan a cab journey <span>↗</span></button></div><div class="route-list">{routes}</div></div>{fleet}</div></section>'
def journal(all=False):
 arts=data['articles'] if all else [data['articles'][1],data['articles'][2],data['articles'][4]]
 return '<section class="section wrap">'+(heading('The Kerala journal','Good places.<br><em>Better stories.</em>','A little inspiration for your next Kerala journey.') if not all else '')+'<div class="journal-grid">'+''.join(f'<a class="journal-card" href="/blog/{a["slug"]}" data-reveal><div class="journal-image">{img(a["image"],a["alt"])}</div><span class="article-category">{a["category"]}</span><h3>{a["title"]}</h3><span class="text-link">Read the story ↗</span></a>' for a in arts)+'</div>'+('' if all else '<div class="section-end">'+btn('Read the Kerala journal','/blog')+'</div>')+'</section>'
hero=f'''<section class="hero">{video('kerala-backwaters.mp4','hero-poster.jpg','Kumarakom backwaters, Kerala Tourism')}<div class="hero-clouds" aria-hidden="true"><div class="hero-cloud cloud-left"><img src="/assets/clouds/cloud-left.png" alt="" width="1972" height="1282"></div><div class="hero-cloud cloud-center"><img src="/assets/clouds/cloud-soft.png" alt="" width="2216" height="1182"></div><div class="hero-cloud cloud-right"><img src="/assets/clouds/cloud-soft.png" alt="" width="2216" height="1182"></div></div><div class="hero-content">{eyebrow('Fort Kochi beginnings. Kerala memories.')}<h1>Life is better<br>by the <em>backwaters.</em></h1><p>Quiet canals. Village stories. A day in Kerala<br class="desktop-break"> that stays with you long after you leave.</p>{btn('Discover the Vaikom experience','/tour','light')}</div><div class="hero-bottom"><span>09°45′ N &nbsp; 76°24′ E<br>VAIKOM · KERALA</span><a href="#discover">Take the slow route ↓</a><span class="film-credit">Kumarakom film · Kerala Tourism</span></div></section>'''
dest=f'''<section class="section wrap destination"><div class="destination-photo" data-reveal>{img('alappuzha.webp','Palm-lined Alappuzha backwaters')}<span class="destination-caption">ALAPPUZHA, KERALA</span></div><div class="destination-copy" data-reveal>{eyebrow('One place leads to another')}<h2>A little more<br>of <em>Kerala.</em></h2><p>From the waterways to the hills, leave room for a few more beautiful detours.</p><a href="/blog/fort-kochi-waterfront" class="place-row"><span>01</span> Fort Kochi <b>↗</b></a><a href="/blog/munnar-hill-escape" class="place-row"><span>02</span> Munnar <b>↗</b></a><a href="/blog/athirappilly-waterfalls" class="place-row"><span>03</span> Athirappilly <b>↗</b></a></div></section>'''
# Home uses distinct still images across its cards, gallery, destination and journal.
save(Path('.'),'Vaikom backwaters & Kerala journeys',hero+promise()+f'<section class="section wrap" id="discover">{heading("A day, many discoveries","Kerala, beyond<br>the <em>postcard.</em>","Part of one thoughtfully paced Vaikom day. Boat rides, local traditions and a taste of Kerala.")}{cards(experiences[:3])}</section>'+ribbon()+dest+stats()+gallery()+cabsection()+journal(),True)
save(Path('tours'),'Village experiences',intro('Discover Vaikom','A day full of<br><em>little discoveries.</em>','Every experience below is part of the full-day Vaikom village tour. Choose a theme to explore.')+'<section class="wrap section compact"><div class="filters" role="group" aria-label="Filter village experiences">'+''.join(f'<button data-filter="{c}" aria-pressed="{str(i==0).lower()}">{c}</button>' for i,c in enumerate(['All experiences','Backwaters','Local crafts','Kerala lunch','Village life','Boat rides']))+'</div>'+cards(experiences)+'</section>'+stats())
save(Path('tour'),'The full-day Vaikom experience',intro('Daily departures · Vaikom, Kerala','An unhurried day.<br><em>An unforgettable place.</em>','Bamboo boats, village craft traditions and a Kerala lunch — with pickup and return to your hotel.')+stats()+f'<section class="section wrap">{heading("Small moments. Lasting memories.","Your day in <em>Vaikom.</em>")}{cards(experiences[:3])}<div class="included-note"><h3>More to discover ashore</h3><p>The village programme also includes mat weaving, coconut leaf weaving for thatched roofing and a handmade cloth weaving centre visit.</p></div></section>'+gallery()+cabsection())
save(Path('traveler-stories'),'Village gallery',intro('The village gallery','Real places.<br><em>Shared moments.</em>','A closer look at Arafath’s village waterways and the people who make the experience special.')+gallery(True))
save(Path('cabs'),'Kerala cab facilities',intro('Airport · Local · Outstation','Your journey.<br><em>Our way of caring.</em>','Comfortable connections from Fort Kochi to Kerala’s backwaters, hills and airport.')+cabsection(True))
save(Path('blog'),'Kerala journal',intro('Notes from Kerala','A place for<br><em>curious travellers.</em>','Backwater life, village traditions and beautiful places worth getting to know.')+journal(True))
save(Path('journal'),'Kerala journal',intro('Notes from Kerala','Stories for the<br><em>journey ahead.</em>','Explore Kerala through local experiences, thoughtful outings and landscape guides.')+journal(True))
from explore import render_explore
save(Path('location'),'Explore Kerala — An interactive 3D atlas',render_explore())
save(Path('about'),'About Arafath Tours',intro('Arafath Tours & Travels','A local beginning.<br><em>A lasting memory.</em>','Based in Fort Kochi, Arafath brings you closer to Vaikom’s village backwaters and the people along the way.')+promise()+f'<section class="section wrap about-layout">{img("vaikom-32-1.jpg","A visitor sharing a village craft moment")}<div>{eyebrow("Arafath Rent a Bike Tours & Travels")}<h2>See the place.<br><em>Meet its people.</em></h2><p>Our full-day Vaikom experience brings together time on the water, village craft visits and a traditional Kerala lunch. Hotel pickup and drop-off make it easy to settle into the day.</p><p>Alongside the village tour, ask us about airport transfers, local cab facilities and outstation journeys across Kerala.</p>{btn("Talk to the local team","/contact")}</div></section>')
contact=f'''<section class="section wrap contact-grid"><div>{eyebrow('Let’s make it happen')}<h2>Tell us your<br><em>travel plans.</em></h2><p>A date, a place, an idea. Start with a conversation and we’ll help you plan the details.</p><a class="contact-link" href="tel:+919947478328">+91 99474 78328 ↗</a><a class="contact-link email" href="mailto:Arafathappu52@gmail.com">Arafathappu52@gmail.com ↗</a><p>Fort Kochi, Kerala, India</p></div><form class="enquiry-form" id="tour-form"><label>Your name<input name="Name" autocomplete="name" required></label><label>Phone / WhatsApp<input type="tel" name="Phone" autocomplete="tel" required></label><label>Preferred date<input name="Date" type="date" required></label><label>Number of guests<input name="Guests" type="number" min="1" value="2" required></label><label class="wide">Your hotel / pickup location<input name="Hotel" required></label><label class="wide">What would you like to plan?<textarea name="Message" rows="4" placeholder="Vaikom village tour, a cab journey, or a little of both…" required></textarea></label><button class="button wide" type="submit">Continue on WhatsApp <span>↗</span></button><small class="wide">You can review and send your enquiry in WhatsApp. Availability is confirmed directly by the team.</small></form></section>'''
save(Path('contact'),'Plan your Kerala trip',intro('Your next story starts here','Let’s go<br><em>somewhere lovely.</em>','Get in touch with Arafath Tours in Fort Kochi.')+contact)
for a in data['articles']:
 body=intro(a['category'],esc(a['title']),a['intro'])+f'<article class="article wrap"><figure>{img(a["image"],a["alt"])}<figcaption>{esc(a["alt"])}</figcaption></figure><div class="article-copy">'+''.join(f'<section><h2>{esc(t)}</h2><p>{esc(p)}</p></section>' for t,p in a['sections'])+f'<a class="source-link" href="{a["source"]}" target="_blank" rel="noopener">Further reading / source ↗</a><div class="article-actions">{btn("Plan your Kerala journey","/contact")}<a href="/blog">← All stories</a></div></div></article>'
 save(Path('blog')/a['slug'],a['title'],body)
# Typeface declarations are stored with the source and use local font assets.
(D/'fonts.css').write_text((ROOT/'src/fonts.css').read_text())
print('Rebuilt',len(list(D.rglob('index.html'))),'page entrypoints')
